"""Official competition entrypoint and compatibility re-export facade."""
from __future__ import annotations

import time  # compatibility for existing patch targets

from reasoning_agent.policy import (
    TASK_TYPE_CHOICE,
    TASK_TYPE_FILL_BLANK,
    TASK_TYPE_CALCULATION,
    TASK_TYPE_DERIVATION,
    TASK_TYPE_PROOF,
    TASK_TYPE_EXPLANATION,
    POLICY_PROMPT,
    ANSWER_FIRST_POLICY_PROMPT,
    ANSWER_ONLY_POLICY_PROMPT,
    VERIFIER_PROMPT,
    SUBSTITUTION_CHECK_PROMPT,
    CHOICE_PROMPT,
    FILL_BLANK_PROMPT,
    CALCULATION_PROMPT,
    NUMERIC_ANSWER_FIRST_PROMPT,
    NUMERIC_COD_ANSWER_FIRST_PROMPT,
    DERIVATION_PROMPT,
    PROOF_PROMPT,
    EXPLANATION_PROMPT,
    DIRECT_REASONER_PROMPT,
    ALTERNATIVE_REASONER_PROMPT,
    STEP_VERIFY_PROMPT,
    SOLUTION_VERIFY_PROMPT,
    STEP_REVISE_PROMPT,
    GSA_AGGREGATE_PROMPT,
    GATED_TRUNCATION_INSTRUCTION,
    GATED_UNSTRUCTURED_INSTRUCTION,
    GATED_PLACEHOLDER_INSTRUCTION,
    GATED_CONFLICT_INSTRUCTION,
    GATED_SANITY_INSTRUCTION,
    TASK_PROMPTS,
    _NON_NUMERIC_TASK_TYPES,
    classify_problem_type,
    AgentConfig,
    SUBMISSION_CONFIG,
)

from reasoning_agent.answers import (
    _ANSWER_MARKER_RE,
    _ANSWER_MARKER_LINE_STRICT_RE,
    _CHOICE_LINE_RE,
    _MATH_ONLY_LINE_RE,
    _CONNECTIVE_RE,
    _STRICT_THINKING_RE,
    extract_final_answer,
    extract_answer_first,
    extract_numeric_answer,
    _extract_standalone_boxed_answer,
    _is_strict_numeric_value,
    _ANSWER_MARKER_POS_RE,
    _ANSWER_SEGMENT_STOP_RE,
    _BODY_HEADER_RE,
    _ANSWER_ECHO_RE,
    _THINKING_CONTEXT_RE,
    extract_answer_segment,
    _is_marker_in_thinking_quote,
    _take_answer_segment,
    _is_answer_echo,
    _BODY_HEADER_NAME,
    reconstruct_final_response,
    _ANSWER_MARKER_LINE_RE,
    _BODY_HEADER_LINE_RE,
    _PLACEHOLDER_RE,
    _is_placeholder_segment,
    parse_structure_f,
    reconstruct_final_response_f,
    _is_answer_like,
    _is_standalone_answer_line,
    _has_placeholder_answer,
    is_placeholder_answer,
    _SALVAGE_BOXED_RE,
    _SALVAGE_MARKER_RE,
    _SALVAGE_NUMBER_RE,
    _SALVAGE_MAX_CHARS,
    _salvage_answer,
    _truncation_signals,
    _extract_boxed_answers,
    _format_rational,
    _parse_rational_token,
    _canonicalize_multi_numeric_set,
    normalize_answer,
    answer_equivalence,
    has_conflicting_explicit_answers,
    _conflicting_answer_pair,
    _single_scalar_value,
    _GATE_INTERROGATIVE_RE,
    _GATE_PROBABILITY_RE,
    _GATE_EXPECTATION_RE,
    _GATE_COUNT_RE,
    _GATE_AVERAGE_RE,
    _interrogative_sentences,
    _sanity_violation,
    _GATE_MODE_PRIORITY,
    run_answer_checks,
)

from reasoning_agent.runtime import ReasoningAgent
