"""Frozen generic contract cases for Host Loop foundations acceptance.

The rows use only synthetic structures.  They do not copy public-set idx values,
problem text, gold answers, or source tags.
"""

from __future__ import annotations

SEED = 20260907
MAX_PROBLEM_CHARS = 12_000
SECRET = "SENSITIVE_METADATA_VALUE_9f3c"


def fesf_packets():
    return [
        "SKILL_CHOICE: NONE\nAPPLICABILITY: NO\nGOAL: 求唯一值\nANSWER_TYPE: 数值\nCONSTRAINTS: 等式",
        "BRANCH: B\nCLAIMS:\nB1: 1+2=3\nCANDIDATE_B: 3\nOPEN: 检查代回",
        "BRANCH: C\nCLAIMS:\nC1: 1+2=3\nCANDIDATE_C: 3\nOPEN: 无",
        "PRIMARY_BRANCH: B\nPRIMARY_REASON: B 覆盖约束\nSUPPORTED_CLAIMS: none\nAUXILIARY_CLAIMS: none\nREFUTED_CLAIMS: none\nUNRESOLVED_CLAIMS: B1, C1\nCANDIDATE_D: 3\nOPEN: 完成",
        "FINAL: 3",
    ]


INTAKE_CASES = [
    {"id": "I01", "kind": "normalize", "problem": "\u00e9", "expect": "é"},
    {"id": "I02", "kind": "normalize", "problem": "e\u0301", "expect": "é"},
    {"id": "I03", "kind": "normalize", "problem": "a\r\nb\r", "expect": "a\nb"},
    {"id": "I04", "kind": "normalize", "problem": "\u200bx = 1\ufeff", "expect": "x = 1"},
    {"id": "I05", "kind": "normalize", "problem": "x\x00=\x07 1", "expect": "x= 1"},
    {"id": "I06", "kind": "error", "fn": "normalize", "problem": " \n\t", "error": "problem_empty"},
    {"id": "I07", "kind": "error", "fn": "normalize", "problem": "", "error": "problem_empty"},
    {"id": "I08", "kind": "normalize", "problem": "x" * MAX_PROBLEM_CHARS, "expect": "x" * MAX_PROBLEM_CHARS},
    {"id": "I09", "kind": "error", "fn": "normalize", "problem": "x" * (MAX_PROBLEM_CHARS + 1), "error": "problem_too_long"},
    {"id": "I10", "kind": "error", "fn": "complexity", "problem": "a" * (MAX_PROBLEM_CHARS + 1), "error": "problem_too_long"},
    {"id": "I11", "kind": "error", "fn": "intake", "problem": "x" * (MAX_PROBLEM_CHARS + 1), "error": "problem_too_long"},
    {"id": "I12", "kind": "error", "fn": "intake", "problem": 12, "error": "problem_type"},
    {
        "id": "I13",
        "kind": "metadata",
        "metadata": {
            "idx": 3,
            "question_id": "q-3",
            "task_id": "t-3",
            "split": "dev",
            "language": "zh",
            "difficulty": 1.5,
            "source": "synthetic",
            "domain": "algebra",
            "category": "short",
        },
        "expect_keys": [
            "idx",
            "question_id",
            "task_id",
            "split",
            "language",
            "difficulty",
            "source",
            "domain",
            "category",
        ],
        "expect_reasons": [],
    },
    {
        "id": "I14",
        "kind": "metadata",
        "metadata": {"idx": 1, "answer": SECRET, "gold": SECRET, "solution": SECRET},
        "expect_keys": ["idx"],
        "expect_reasons": ["sensitive_key"],
        "forbidden": SECRET,
    },
    {
        "id": "I15",
        "kind": "metadata",
        "metadata": {"idx": 1, "unknown": "value", "extra": True},
        "expect_keys": ["idx"],
        "expect_reasons": ["not_allowlisted"],
    },
    {
        "id": "I16",
        "kind": "metadata",
        "metadata": {"idx": [1, 2], "language": {"zh": True}},
        "expect_keys": [],
        "expect_reasons": ["non_scalar"],
    },
    {
        "id": "I17",
        "kind": "metadata",
        "metadata": {"difficulty": float("nan"), "idx": float("inf")},
        "expect_keys": [],
        "expect_reasons": ["non_finite"],
    },
    {
        "id": "I18",
        "kind": "metadata",
        "metadata": {f"idx{i}": i for i in range(20)} | {"idx": 1},
        "expect_reasons_contains": "field_limit",
    },
    {
        "id": "I19",
        "kind": "metadata",
        "metadata": {"language": "x" * 257},
        "expect_keys": [],
        "expect_reasons": ["value_too_long"],
    },
    {
        "id": "I20",
        "kind": "metadata",
        "metadata": {"!!!": "bad", "": "empty"},
        "expect_keys": [],
        "expect_reasons": ["invalid_key"],
    },
    {
        "id": "I21",
        "kind": "metadata",
        "metadata": ["not", "a", "mapping"],
        "expect_keys": [],
        "expect_reasons": ["metadata_type"],
    },
    {"id": "I22", "kind": "metadata", "metadata": None, "expect_keys": [], "expect_reasons": []},
    {"id": "I23", "kind": "error", "fn": "intake", "problem": "x=1", "answer_type": "t" * 65, "error": "answer_type_too_long"},
    {"id": "I24", "kind": "intake_profile", "problem": "计算 1+2", "profile": "short", "proof": False, "universal": False},
    {
        "id": "I25",
        "kind": "intake_profile",
        "problem": "证明任意 x 满足等式。\n1. 第一问\n2. 第二问",
        "profile": "structured",
        "proof": True,
        "universal": True,
        "parts": True,
    },
    {
        "id": "I26",
        "kind": "intake_profile",
        "problem": "a" * 2001,
        "profile": "long",
        "proof": False,
        "universal": False,
    },
    {
        "id": "I27",
        "kind": "metadata",
        "metadata": {"idx": 0, "language": True, "difficulty": 2},
        "expect_keys": ["idx", "language", "difficulty"],
        "expect_reasons": [],
    },
    {
        "id": "I28",
        "kind": "intake_secret",
        "problem": "证明任意 x 时 1+1=2",
        "metadata": {"idx": 1, "gold": SECRET, "answer": SECRET, "hidden_answer": SECRET},
        "forbidden": SECRET,
    },
    {
        "id": "I29",
        "kind": "repeat",
        "problem": "证明任意 x != 0 时 1/x = 1/x。",
        "metadata": {"idx": 9, "gold": SECRET, "domain": "algebra"},
        "repeats": 20,
    },
    {
        "id": "I30",
        "kind": "metadata",
        "metadata": {"language": "x" * 256},
        "expect_keys": ["language"],
        "expect_reasons": [],
    },
]


OBLIGATION_CASES = [
    {"id": "O01", "problem": "计算 1+2 的值。", "kinds": [], "truncated": False},
    {"id": "O02", "problem": "证明该等式成立。", "kinds": ["PROOF_COMPLETENESS"], "truncated": False},
    {"id": "O03", "problem": "对任意 x 验证该性质。", "kinds": ["UNIVERSAL_COVERAGE"], "truncated": False},
    {"id": "O04", "problem": "存在至少一个满足条件的解。", "kinds": ["EXISTENCE_WITNESS"], "truncated": False},
    {"id": "O05", "problem": "枚举所有情形并分类讨论。", "kinds": ["UNIVERSAL_COVERAGE", "FINITE_COVERAGE"], "truncated": False},
    {"id": "O06", "problem": "将候选代回原方程检验。", "kinds": ["SUBSTITUTION_CHECK"], "truncated": False},
    {"id": "O07", "problem": "给出变量定义域后再求解。", "kinds": ["DOMAIN_SPECIFICATION"], "truncated": False},
    {"id": "O08", "problem": "求全部实根与所有解。", "kinds": ["UNIVERSAL_COVERAGE", "ENUMERATE_ALL_SOLUTIONS"], "truncated": False},
    {
        "id": "O09",
        "problem": "OPEN: 检查边界\nOBLIGATION: 覆盖全部情形\n未决义务: 代回检验",
        "kinds": ["OPEN_ITEM", "OPEN_ITEM", "OPEN_ITEM", "UNIVERSAL_COVERAGE", "SUBSTITUTION_CHECK"],
        "truncated": False,
    },
    {"id": "O10", "problem": "化简 1/x 。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"], "truncated": False},
    {"id": "O11", "problem": "已知 x != 0，化简 1/x 。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"], "truncated": False},
    {"id": "O12", "problem": "计算 (x+1)/y 的值。", "kinds": ["DOMAIN_CHECK"], "truncated": False},
    {"id": "O13", "problem": "速度单位是 km/h 。", "kinds": [], "truncated": False},
    {"id": "O14", "problem": "选择 and/or 中的一种表述。", "kinds": [], "truncated": False},
    {"id": "O15", "problem": "这是一个没有数学触发词的普通句子。", "kinds": [], "truncated": False},
    {
        "id": "O16",
        "problem": "\n".join(
            [
                "OPEN: a",
                "OPEN: b",
                "OPEN: c",
                "证明任意 x，存在至少一个解，枚举全部解并代回。",
                "给出定义域与所有解。",
                "1/x",
            ]
        ),
        "max_items": 8,
        "max_len": 8,
        "truncated": True,
    },
    {
        "id": "O17",
        "problem": "证明证明 prove show that",
        "kinds": ["PROOF_COMPLETENESS"],
        "truncated": False,
    },
    {"id": "O18", "problem": "OPEN: same\nOPEN: same", "kinds": ["OPEN_ITEM"], "ids": ["O1"], "truncated": False},
    {"id": "O19", "kind": "error", "problem": "x" * 12_001, "error": "problem_too_long"},
    {"id": "O20", "problem": "1/x 且 x 非零", "kinds": ["DOMAIN_CHECK", "DOMAIN_SPECIFICATION"], "states": ["OPEN", "OPEN"]},
    {
        "id": "O21",
        "problem": "\n".join(["OPEN: a", "OPEN: b", "证明任意 x，存在至少一个解，枚举全部解并代回。", "1/x"]),
        "max_items": 2,
        "max_len": 2,
        "ids": ["O1", "O2"],
        "truncated": True,
    },
    {
        "id": "O22",
        "problem": "prove that for all x there exists a witness",
        "kinds": ["PROOF_COMPLETENESS", "UNIVERSAL_COVERAGE", "EXISTENCE_WITNESS"],
    },
    {
        "id": "O23",
        "problem": "check by substitution after enumerate",
        "kinds": ["FINITE_COVERAGE", "SUBSTITUTION_CHECK"],
    },
    {"id": "O24", "problem": "unknown prose without slash or keywords", "kinds": []},
    {"id": "O25", "problem": "OPEN: 检查边界", "kinds": ["OPEN_ITEM"], "ids": ["O1"]},
    {"id": "O26", "problem": "已知 x != 0，化简 (x-1)/(x-1)。", "kinds": []},
    {"id": "O27", "problem": "已知 x != 0，化简 1/(x-1)。", "kinds": []},
    {"id": "O28", "problem": "计算 (x+1)/y 的值。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O29", "problem": "已知 max != 0，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O30", "problem": "已知 index != 0，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O31", "problem": "已知 xy != 0，化简 1/y。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O32", "problem": "已知 x != 0.5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O33", "problem": "已知 x != 0+1，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O34", "problem": "已知 x != 0-1，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O35", "problem": "已知 x不等于0.5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O36", "problem": "已知 x不等于0点5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O37", "problem": "已知 x != 0点5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O38", "problem": "已知 x != 0．5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O39", "problem": "已知 x != 0·5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O40", "problem": "已知 x != 0／5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O41", "problem": "已知 x != 0/5，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O42", "problem": "已知 x != 0 and y != 0，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O43", "problem": "已知 x*y != 0，化简 1/x。", "kinds": ["DOMAIN_CHECK"], "states": ["OPEN"]},
    {"id": "O44", "problem": "化简 1/(x*y)。", "kinds": []},
    {"id": "O45", "problem": "已知 x != 0 且 y != 0，化简 1/(x*y)。", "kinds": []},
]



SYMBOLIC_CASES = [
    {"id": "S01", "op": "eq", "left": "(x+1)*(x-1)", "right": "x**2-1", "status": "EXACT"},
    {"id": "S02", "op": "eq", "left": "x+x", "right": "2*x", "status": "EXACT"},
    {"id": "S03", "op": "eq", "left": "(x+y)*(x+y)", "right": "x**2+2*x*y+y**2", "status": "EXACT"},
    {"id": "S04", "op": "eq", "left": "0", "right": "0", "status": "EXACT"},
    {"id": "S05", "op": "eq", "left": "1", "right": "1", "status": "EXACT"},
    {"id": "S06", "op": "eq", "left": "x", "right": "x", "status": "EXACT"},
    {"id": "S07", "op": "eq", "left": "x+1", "right": "x+2", "status": "REFUTED"},
    {"id": "S08", "op": "eq", "left": "2*x", "right": "x", "status": "UNKNOWN"},
    {"id": "S09", "op": "eq", "left": "1", "right": "0", "status": "REFUTED"},
    {"id": "S10", "op": "eq", "left": "x**2", "right": "x**2+1", "status": "REFUTED"},
    {"id": "S11", "op": "rel", "left": "x+1", "relation": ">=", "right": "x", "status": "EXACT"},
    {"id": "S12", "op": "rel", "left": "x", "relation": "<", "right": "x+1", "status": "EXACT"},
    {"id": "S13", "op": "rel", "left": "x", "relation": ">", "right": "x+1", "status": "REFUTED"},
    {"id": "S14", "op": "rel", "left": "x", "relation": "==", "right": "x", "status": "EXACT"},
    {"id": "S15", "op": "rel", "left": "x", "relation": "!=", "right": "x", "status": "REFUTED"},
    {"id": "S16", "op": "eq", "left": "1/x", "right": "1/x", "status": "UNKNOWN"},
    {"id": "S17", "op": "eq", "left": "1/x", "right": "1/x", "assumptions": ["x != 0"], "status": "EXACT"},
    {"id": "S18", "op": "eq", "left": "1/(x+y)", "right": "1/(x+y)", "status": "UNKNOWN"},
    {"id": "S19", "op": "eq", "left": "x**(-1)", "right": "1/x", "status": "UNKNOWN"},
    {"id": "S20", "op": "eq", "left": "x**(-1)", "right": "1/x", "assumptions": ["x != 0"], "status": "EXACT"},
    {"id": "S21", "op": "eq", "left": "x**13", "right": "x**13", "status": "UNKNOWN"},
    {"id": "S22", "op": "eq", "left": "x**(-2)", "right": "1/(x*x)", "status": "UNKNOWN"},
    {"id": "S23", "op": "eq", "left": "sin(x)", "right": "sin(x)", "status": "UNKNOWN"},
    {"id": "S24", "op": "eq", "left": "foo(x)", "right": "1", "status": "UNKNOWN"},
    {"id": "S25", "op": "eq", "left": "x.real", "right": "x", "status": "UNKNOWN"},
    {"id": "S26", "op": "eq", "left": "__import__('os')", "right": "1", "status": "UNKNOWN"},
    {"id": "S27", "op": "eq", "left": "x=1", "right": "1", "status": "UNKNOWN"},
    {"id": "S28", "op": "eq", "left": "+".join(["x"]*80), "right": "x", "status": "UNKNOWN"},
    {"id": "S29", "op": "eq", "left": "x[0]", "right": "x", "status": "UNKNOWN"},
    {"id": "S30", "op": "eq", "left": "abs(x)", "right": "abs(x)", "status": "UNKNOWN"},
    {"id": "S31", "op": "rel", "left": "x", "relation": "??", "right": "x", "status": "UNKNOWN"},
    {"id": "S32", "op": "eq", "left": "", "right": "1", "status": "UNKNOWN"},
    {"id": "S33", "op": "eq", "left": "(x-1)/(x-1)", "right": "1", "assumptions": ["x != 0"], "status": "UNKNOWN"},
    {"id": "S34", "op": "eq", "left": "(x-1)/(x-1)", "right": "1", "assumptions": ["x != 1"], "status": "UNKNOWN"},
    {"id": "S35", "op": "eq", "left": "1/(x-1)", "right": "1/(x-1)", "assumptions": ["x != 0"], "status": "UNKNOWN"},
    {"id": "S36", "op": "eq", "left": "1/(x+y)", "right": "1/(x+y)", "assumptions": ["x != 0", "y != 0"], "status": "UNKNOWN"},
    {"id": "S37", "op": "eq", "left": "x**(0-1)", "right": "x**(0-1)", "status": "UNKNOWN"},
    {"id": "S38", "op": "eq", "left": "x**(1-2)", "right": "x**(1-2)", "status": "UNKNOWN"},
    {"id": "S39", "op": "eq", "left": "x**(-1*1)", "right": "x**(-1*1)", "status": "UNKNOWN"},
    {"id": "S40", "op": "eq", "left": "x**(0-1)", "right": "x**(0-1)", "assumptions": ["x != 0"], "status": "EXACT"},
    {"id": "S41", "op": "eq", "left": "x**(1/-1)", "right": "x**(1/-1)", "status": "UNKNOWN"},
    {"id": "S42", "op": "eq", "left": "x**(1/-1)", "right": "x**(1/-1)", "assumptions": ["x != 0"], "status": "UNKNOWN"},
    {"id": "S43", "op": "eq", "left": "x**-1", "right": "x**-1", "status": "UNKNOWN"},
    {"id": "S44", "op": "eq", "left": "x**(-1+0)", "right": "x**(-1+0)", "status": "UNKNOWN"},
    {"id": "S45", "op": "eq", "left": "(x+y)**(-1)", "right": "(x+y)**(-1)", "assumptions": ["x != 0", "y != 0"], "status": "UNKNOWN"},
]


FINITE_CASES = [
    {"id": "F01", "var": "x", "pred": "x % 2 == 0", "values": [0, 2, 4], "status": "EXACT"},
    {"id": "F02", "var": "x", "pred": "x % 2 == 0", "values": [1, 2, 4], "status": "REFUTED", "witness": "x=1"},
    {"id": "F03", "var": "x", "pred": "x % 2 == 0", "values": [2, 4, 5], "status": "REFUTED", "witness": "x=5"},
    {"id": "F04", "var": "x", "pred": "x == 0", "values": [], "status": "UNKNOWN"},
    {"id": "F05", "var": "x", "pred": "x == 0", "values": list(range(65)), "status": "UNKNOWN"},
    {"id": "F06", "var": "_x", "pred": "x == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "F07", "var": "1x", "pred": "x == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "F08", "var": "", "pred": "x == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "F09", "var": "x", "pred": "x == 1/2", "values": ["1/2"], "status": "EXACT"},
    {"id": "F10", "var": "x", "pred": "1/x == 1", "values": [0], "status": "UNKNOWN"},
    {"id": "F11", "var": "x", "pred": "x ** 11 == 0", "values": [0], "status": "UNKNOWN"},
    {"id": "F12", "var": "x", "pred": "x == 1", "values": [True], "status": "UNKNOWN"},
    {"id": "F13", "var": "x", "pred": "x == 1", "values": [1.5], "status": "UNKNOWN"},
    {"id": "F14", "var": "x", "pred": "x == 1", "values": ["1.5"], "status": "UNKNOWN"},
    {"id": "F15", "var": "x", "pred": "x > 0", "values": [1, 2, 3], "status": "EXACT"},
    {"id": "F16", "var": "x", "pred": "x > 0", "values": [1, 0], "status": "REFUTED", "witness": "x=0"},
    {"id": "F17", "var": "x", "pred": "x == 1 and x != 2", "values": [1], "status": "EXACT"},
    {"id": "F18", "var": "x", "pred": "not (x == 0)", "values": [1], "status": "EXACT"},
    {"id": "F19", "var": "x", "pred": "__import__('os')", "values": [0], "status": "UNKNOWN"},
    {"id": "F20", "var": "x", "pred": "x.real == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "F21", "var": "x", "pred": "foo(x) == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "F22", "var": "x", "pred": "x = 1", "values": [1], "status": "UNKNOWN"},
    {"id": "F23", "var": "x", "pred": "x == 1", "values": [10**10], "status": "UNKNOWN"},
    {"id": "F24", "var": "x", "pred": "x // 2 == 1", "values": [2], "status": "EXACT"},
    {"id": "F25", "var": "x", "pred": "x % 0 == 0", "values": [1], "status": "UNKNOWN"},
    {"id": "F26", "var": "x", "pred": "x == x", "values": [-3, 0, 7], "status": "EXACT"},
    {"id": "F27", "var": "x", "pred": "x != x", "values": [1], "status": "REFUTED", "witness": "x=1"},
    {"id": "F28", "var": "x", "pred": " and ".join(["x==1"]*80), "values": [1], "status": "UNKNOWN"},
    {"id": "F29", "var": "x", "pred": "", "values": [1], "status": "UNKNOWN"},
    {"id": "F30", "var": "x", "pred": "x >= 0", "values": [0, 1, 2], "status": "EXACT"},
    {"id": "F31", "var": "x", "pred": "x < 0 or x > 0", "values": [-1, 1], "status": "EXACT"},
    {"id": "F32", "var": "y", "pred": "y == 2", "values": [2], "status": "EXACT"},
]


COUNTEREXAMPLE_CASES = [
    {"id": "K01", "var": "x", "pred": "x != 0", "values": [0, 1], "status": "REFUTED", "witness": "x=0"},
    {"id": "K02", "var": "x", "pred": "x * x >= 0", "values": [-2, -1, 0, 1, 2], "status": "UNKNOWN"},
    {"id": "K03", "var": "x", "pred": "foo(x) == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "K04", "var": "x", "pred": "x == 0", "values": [], "status": "UNKNOWN"},
    {"id": "K05", "var": "x", "pred": "x % 2 == 0", "values": [1, 3], "status": "REFUTED", "witness": "x=1"},
    {"id": "K06", "var": "x", "pred": "x % 2 == 0", "values": [2, 4, 6], "status": "UNKNOWN"},
    {"id": "K07", "var": "x", "pred": "x > 0", "values": [1, 2], "status": "UNKNOWN"},
    {"id": "K08", "var": "x", "pred": "x > 0", "values": [0], "status": "REFUTED", "witness": "x=0"},
    {"id": "K09", "var": "_x", "pred": "x == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "K10", "var": "x", "pred": "__import__('os')", "values": [0], "status": "UNKNOWN"},
    {"id": "K11", "var": "x", "pred": "x.real == 1", "values": [1], "status": "UNKNOWN"},
    {"id": "K12", "var": "x", "pred": "x = 1", "values": [1], "status": "UNKNOWN"},
    {"id": "K13", "var": "x", "pred": "1/x == 1", "values": [0], "status": "UNKNOWN"},
    {"id": "K14", "var": "x", "pred": "x == 1", "values": list(range(65)), "status": "UNKNOWN"},
    {"id": "K15", "var": "x", "pred": "x != x", "values": [3], "status": "REFUTED", "witness": "x=3"},
    {"id": "K16", "var": "x", "pred": "x == x", "values": [3], "status": "UNKNOWN"},
    {"id": "K17", "var": "x", "pred": "not (x == 0)", "values": [0], "status": "REFUTED", "witness": "x=0"},
    {"id": "K18", "var": "x", "pred": "not (x == 0)", "values": [1, 2], "status": "UNKNOWN"},
    {"id": "K19", "var": "x", "pred": "x >= 0", "values": [-1, 0], "status": "REFUTED", "witness": "x=-1"},
    {"id": "K20", "var": "x", "pred": "x >= 0", "values": [0, 1], "status": "UNKNOWN"},
    {"id": "K21", "var": "x", "pred": "", "values": [1], "status": "UNKNOWN"},
    {"id": "K22", "var": "x", "pred": "x == 1/2", "values": ["1/2"], "status": "UNKNOWN"},
    {"id": "K23", "var": "x", "pred": "x == 1/2", "values": ["1/3"], "status": "REFUTED", "witness": "x=1/3"},
    {"id": "K24", "var": "y", "pred": "y != 4", "values": [4], "status": "REFUTED", "witness": "y=4"},
    {"id": "K25", "var": "y", "pred": "y != 4", "values": [1, 2], "status": "UNKNOWN"},
    {"id": "K26", "var": "x", "pred": "x < 0", "values": [1, 2, 3], "status": "REFUTED", "witness": "x=1"},
    {"id": "K27", "var": "x", "pred": "x < 0", "values": [-3, -1], "status": "UNKNOWN"},
    {"id": "K28", "var": "x", "pred": "foo(x) == 1", "values": [0, 1, 2], "status": "UNKNOWN"},
    {"id": "K29", "var": "x", "pred": "x == 1 and x == 2", "values": [1], "status": "REFUTED", "witness": "x=1"},
    {"id": "K30", "var": "x", "pred": "x == 1 or x == 2", "values": [1, 2], "status": "UNKNOWN"},
    {"id": "K31", "var": "x", "pred": "x == True", "values": [1], "status": "UNKNOWN"},
    {"id": "K32", "var": "x", "pred": "(" * 80 + "x == 1" + ")" * 80, "values": [1], "status": "UNKNOWN"},
]


NOTEBOOK_VALID_ROWS = [
    {
        "entry_id": "draft-domain",
        "pattern": "symbolic denominator appears without a domain condition",
        "domain": "algebra",
        "mistake": "treating a rational expression as defined everywhere",
        "corrective_rule": "record a non-zero denominator obligation before simplification",
        "use_when": "a denominator contains a symbolic variable",
        "do_not_use": "a denominator is a known non-zero constant",
        "source_trace_ids": ["trace-001"],
        "validation": {"status": "draft", "held_out_total": 0, "held_out_pass": 0},
        "tags": ["domain"],
    },
    {
        "entry_id": "reviewed-finite",
        "pattern": "finite sample mistaken for universal proof",
        "domain": "proof",
        "mistake": "no universal coverage argument",
        "corrective_rule": "treat finite tests as evidence only",
        "use_when": "the claim quantifies over all values",
        "do_not_use": "the problem asks only for a listed finite set",
        "source_trace_ids": ["trace-002"],
        "validation": {"status": "reviewed", "held_out_total": 0, "held_out_pass": 0},
        "tags": ["proof"],
    },
    {
        "entry_id": "validated-holdout",
        "pattern": "missing substitution after solving an equation",
        "domain": "algebra",
        "mistake": "accepting a candidate without substituting back",
        "corrective_rule": "substitute every candidate into the original equation",
        "use_when": "an algebraic equation produced candidate roots",
        "do_not_use": "the task is a pure existence construction",
        "source_trace_ids": ["trace-003"],
        "validation": {"status": "validated", "held_out_total": 2, "held_out_pass": 2},
        "skill_name": "exact-evaluation",
        "tags": ["substitution"],
    },
]
